# Generated by Django 3.2.25 on 2024-11-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20241109_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_images/'),
        ),
    ]
